politicalfeedback_client/apps/accounts/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth.views import logout

urlpatterns = [
	url(r'^registra/$', views.registra),
	url(r'^accedi/$', views.accedi),
	url(r'^errorelogin/$', views.accedierrore),
	url(r'^nonattivo/$', views.nonattivo),
	url(r'^mailesiste/$', views.mailesiste),
	url(r'^recuperauser/$', views.recuperauser),
	url(r'^resetpassword/(?P<confirmation_code>.*)/(?P<idutente>.*)/$', views.resetpassword),
	url(r'^recuperapassword/$', views.recuperapassword),
	url(r'^cambiapassword/$', views.cambiapassword),
	url(r'^passwordcambiata/$', views.passwordcambiata),
	url(r'^errorecambio/$', views.errorecambio),
	url(r'^inviatoutente/$', views.inviatoutente),
	url(r'^dati/$', views.dati),
	url(r'^benvenuto/$', views.benvenuto),
	url(r'^registrato/$', views.registrato),
	url(r'^conferma/(?P<confirmation_code>.*)/(?P<idusername>.*)/$', views.conferma),
	url(r'^nonconfermata/(?P<confirmation_code>.*)/$', views.nonconfermata),
	url(r'^profile/$', views.profile),
	url(r'^rimandaattivazione/$', views.rimandaattivazione),
	url(r'^dashboard/$', views.dashboard),
	url(r'^attivazione/$', views.attivazione),
	url(r'^registrasegnalazione/(?P<reply>\d+)/$', views.registrasegnalazione),
	url(r'^registrasegnalazione/$', views.registrasegnalazione),
	url(r'^segnalazioneinviata/$', views.segnalazioneinviata),
	url(r'^listasegnalazioni/$', views.listasegnalazioni),
	url(r'^elencocitta/(?P<provincia_id>\d+)/$',views.elencocitta),
	url(r'^logout/$', views.logout_view),
	url(r'^member/(?P<id>\d+)/$',views.member),
	url(r'^valuta/(?P<id>\d+)/(?P<valutazione>\d+)/$',views.valuta),

]

politicalfeedback_client/urls.py
from django.conf.urls import  include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

import views

urlpatterns = [
    url(r'^accounts/', include('apps.accounts.urls' )),
    url(r'^pf/', include( 'apps.pf.urls' )),
    url(r'^admin/', admin.site.urls),

    url(r'^gruppo/(?P<id>\d+)/$', views.gruppo ),

    url(r'^$', views.home , name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

	]

politicalfeedback_client/apps/accounts/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Provincia(models.Model):
    codice = models.IntegerField()
    provincia = models.TextField()
    sigla = models.CharField(max_length=4,null=True)

    def __unicode__(self):
        return self.provincia

    def __str__(self):
        return self.provincia


class Comune(models.Model):
    provincia = models.ForeignKey(Provincia)
    codice = models.IntegerField(null=True)
    comune = models.TextField()

    def __unicode__(self):
        return self.comune

    def __str__(self):
        return self.comune



TIPO_UTENTE = (
        (0, 'Simpatizzante'),
        (1, 'Attivista'),
        (2, 'Consigliere o incarico amministrativo'),
		(3, 'Cittadino'),
		(4, 'Cittadino - ostile al gruppo'),
    )


class Profilo(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    attiva_accesso_sito = models.BooleanField(default=False)
    confirmation_code = models.CharField(max_length=50,null=True)
    sitoweb = models.CharField(max_length=120,blank=True,null=True)
    telefono = models.CharField(max_length=120)
    cellulare = models.CharField(max_length=120,blank=True,null=True)
    fax = models.CharField(max_length=120,blank=True,null=True)
    tipo_utente = models.IntegerField(choices = TIPO_UTENTE, default = 0)
    avatar = models.ImageField(upload_to = 'loghi/',null=True)

    indirizzo = models.CharField(max_length=220,blank=True,null=True)
    civico = models.CharField(max_length=15,blank=True,null=True)
    cap = models.CharField(max_length=10,blank=True,null=True)
    citta = models.ForeignKey(Comune)
    provincia = models.ForeignKey(Provincia)


    def __unicode__(self):
        return self.user.first_name

    def __str__(self):
        return self.user.first_name

class Valutazione(models.Model):
	user = models.ForeignKey(User)
	valutazione = models.IntegerField(choices = TIPO_UTENTE, default=0)
	votante = models.ForeignKey(User, related_name="votante")




class Segnalazione(models.Model):
    PRIORITA = (
        (u'Urgente', u'Urgente - il problema mi blocca il lavoro'),
        (u'Media', u'Media - Prima possibile'),
        (u'Bassa', u'Bassa - Con calma, quando possibile'),
    )
    TIPO = (
        (u'Errore', u'Errore nel software'),
        (u'Imprecisione', u'Imprecisione nel software'),
        (u'Miglioramento', u'Suggerisci un miglioramento nel software'),
        (u'Nuova funzione', u'Suggerisci una nuova funzione'),
    )
    STATO = (
        (0, u'Chiuso'),
        (1, u'Aperto'),
        (2, u'Sospeso'),
        (3, u'Inserito nella prossima versione'),
        (4, u'Segnato da fare in futuro'),
        (5, u'Posso farlo, ma a pagamento'),
    )
    MODULO = (
        (1, u'Anagrafiche'),
        (2, u'Contabilita'),
        (3, u'Contabilita - Fatture'),
        (4, u'Contabilita - Documenti Di Trasporto'),
        (5, u'Programmazione'),
        (6, u'Pagamenti'),
        (7, u'Programmazione - Schede'),
        (8, u'Email Automatiche'),
        (9, u'Stampe'),
    )
    user = models.ForeignKey(User,blank=True,null=True)
    data_creazione = models.DateField(auto_now_add=True)
    segnalazione = models.ForeignKey("self",blank=True,null=True, related_name='segnalazione_top')
    priorita = models.CharField(max_length=70,blank=True,null=True,choices=PRIORITA)
    tipo = models.CharField(max_length=70,blank=True,null=True,choices=TIPO)
    oggetto = models.CharField(max_length=120)
    messaggio = models.TextField()
    link = models.URLField(blank=True,null=True)
    screenshot = models.ImageField(upload_to="screeshot",blank=True,null=True)
    stato = models.IntegerField(default=1,choices=STATO,blank=True,null=True)
    modulo = models.IntegerField(choices=MODULO,blank=True,null=True)
    faq = models.NullBooleanField(default=False)
    visto = models.BooleanField(default=False)

politicalfeedback_client/apps/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import Context
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from apps.accounts.forms import *
import random
import string
import datetime
from django.template.loader import get_template
from apps.accounts.models import *
from django.db import transaction
from django.views.decorators.cache import never_cache
from django.db.models import Q, Sum
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import get_object_or_404
from django.db.models import Count, Max

@never_cache
def accedi(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/dashboard/')
	form = LoginForm()
	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)

					# cambio lo stato a seconda delle valutazioni
					n = user.valutazione_set.all().count()
					v = user.valutazione_set.values('valutazione').annotate(conteggio=Count('valutazione')).order_by('conteggio')
					if n >= 2:
						for j in v:
							x = 100*j['conteggio']/n
							if x >= 66:
								user.profilo.tipo_utente = j['valutazione']
								user.profilo.save()


					# Redirect to a success page.
					return HttpResponseRedirect('/accounts/dashboard/')
				else:
				   return HttpResponseRedirect('/accounts/nonattivo/')
			else:
				return HttpResponseRedirect('/accounts/errorelogin/')

	return render(request, 'accounts/login.html', {'form': form } )

def accedierrore(request):
	form = LoginForm()
	return render(request, 'accounts/login.html', {'form': form, 'errore' : True } )

def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/')


@never_cache
def registra(request):
	if request.method == 'POST':
		form = RegistraForm(request.POST, request.FILES)

		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			#obbligatori
			indirizzo = form.cleaned_data['indirizzo']
			civico = form.cleaned_data['civico']
			citta = form.cleaned_data['citta']
			provincia = form.cleaned_data['provincia']
			cap = form.cleaned_data['cap']

			if User.objects.filter(email=email).count() > 0:
				return HttpResponseRedirect('/accounts/mailesiste/')
			else:
				user = User.objects.create_user(email, email, password)
				user.first_name = first_name
				user.last_name = last_name
				user.is_active = False
				user.save()

				confirmation_code = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for x in range(33))
				p = Profilo()
				p.user = user
				p.confirmation_code = confirmation_code
				p.indirizzo = indirizzo
				p.civico = civico
				p.citta = citta
				p.provincia = provincia
				p.cap = cap
				if form.cleaned_data['avatar']:
					p.avatar = form.cleaned_data['avatar']
				p.save()
				send_registration_confirmation(user, get_current_site(request))

				return render(request, 'accounts/registrato.html', {'email': user.email})
	else:
		form = RegistraForm()

	return render(request, 'accounts/registra.html', {'form': form,})

def rimandaattivazione(request):

	if request.method == 'POST':
		form = RecuperaUtente(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			user = User.objects.get(email=email)
			send_registration_confirmation(user, get_current_site(request))
			return render(request, 'accounts/attivazioneinviata.html')
	else:
		return render(request, 'accounts/attivazioneinviata.html')

def nonattivo(request):
	form = RecuperaUtente(request.POST)
	return render(request, 'accounts/nonconfermata.html',{'form': form,})


def recuperauser(request):
	if request.method == 'POST':
		form = RecuperaUtente(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			user = User.objects.get(email=email)
			send_username(user, get_current_site(request))
			return HttpResponseRedirect('/accounts/inviatoutente/')

	return HttpResponseRedirect('/accounts/login/')

def recuperapassword(request):
	if request.method == 'POST':
		form = RecuperaPassword(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			user = User.objects.get(email=email)
			confirmation_code = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for x in range(33))
			p = user.profilo
			p.confirmation_code = confirmation_code
			p.save()
			send_reset_confirmation(user, get_current_site(request))
			return HttpResponseRedirect('/accounts/inviatoutente/')

	return HttpResponseRedirect('/accounts/login/')


def resetpassword(request, confirmation_code, idutente):
	try:
		user = User.objects.get(pk=idutente)
		p = user.profilo
		if p.confirmation_code == confirmation_code:
			return render(request,'accounts/resetpassword.html',{'email': user.email, 'confirmation_code': confirmation_code})
	except:
		return HttpResponseRedirect('/accounts/nonconfermata/'+ confirmation_code + "/")


def cambiapassword(request):
	if request.user.is_authenticated():
		if request.method == 'POST':
			form = CambiaPassword(request.POST)
			if form.is_valid():

				password = form.cleaned_data['password']
				confermapassword = form.cleaned_data['confermapassword']
				if password == confermapassword:
					request.user.set_password(password)
					request.user.save()
					return HttpResponseRedirect('/accounts/passwordcambiata')

	else:
		if request.method == 'POST':
			form = CambiaPasswordReset(request.POST)
			if form.is_valid():
				email = form.cleaned_data['email']
				password = form.cleaned_data['nuovaPassword']
				confirmpassword = form.cleaned_data['confirmPassword']

				confirmation_code = form.cleaned_data['confirmation_code']
				user = User.objects.get(email=email)
				p = user.profilo
				if p.confirmation_code == confirmation_code:
					if password == confirmpassword:
						user.set_password(password)
						user.save()
						return HttpResponseRedirect('/accounts/passwordcambiata')

	return HttpResponseRedirect('/accounts/errorecambio')

def passwordcambiata(request):
	return render(request,'accounts/passwordcambiata.html')

def errorecambio(request):
	return render(request,'accounts/errorecambio.html')

def inviatoutente(request):
	return render(request,'accounts/inviatoutente.html')

def mailesiste(request):
	return render(request,'accounts/mailesiste.html')

def registrato(request):
	return render(request,'accounts/registrato.html')

def dati(request):
	if(is_authenticated()):
		if request.method == 'POST':
			form = FirstAccessForm(request.POST)
			if form.is_valid():
				nome = form.cleaned_data['nome']
				cognome = form.cleaned_data['cognome']
				userid = form.cleaned_data['userid']
				email = form.cleaned_data['email']
				password = form.cleaned_data['passwordvalid']

				if User.objects.filter(email=email).count() > 0:
					return HttpResponseRedirect('/accounts/mailesiste')
				else:

					user = User.objects.create_user(userid, email, password)
					user.first_name = nome
					user.last_name = cognome
					user.is_active = False
					user.save()

					confirmation_code = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for x in range(33))
					p = user.profilo
					p.confirmation_code = confirmation_code
					p.save()
					send_registration_confirmation(user, get_current_site(request))

					return HttpResponseRedirect('/accounts/benvenuto')
		else:
			form = FirstAccessForm()

	return render(request, 'accounts/dati.html', {'form': form,})

def invia_mail(utente, template, to, subject,dominio, from_email=''):
	from django.core.mail import EmailMultiAlternatives
	from django.template.loader import get_template
	from django.template import Context
	from email.MIMEImage import MIMEImage
	from django.conf import settings

	dominio = str(dominio).replace("www.", "")

	d     = Context({ 'nome': utente.first_name, 'cognome': utente.last_name , 'domain': dominio, 'id': utente.id, 'confirmation_code': utente.profilo.confirmation_code })
	plaintext    = get_template('accounts/email/'+template+'.txt')
	htmly        = get_template('accounts/email/'+template+'.html')
	html_content = htmly.render(d)
	text_content = plaintext.render(d)

	if not from_email:
		from_email = settings.EMAIL_CLIENTE

	msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
	msg.attach_alternative(html_content, "text/html")

	#logo
	fp = open(settings.STATIC_ROOT + "/img/logo.png", 'rb')
	msg_img = MIMEImage(fp.read())
	fp.close()
	msg_img.add_header('Content-ID', '<{}>'.format("logo.jpg"))
	msg.attach(msg_img)

	return msg.send()


def send_registration_confirmation(user, dominio):
	title   = _("Conferma account")
	invia_mail(user,'send_registration_confirmation',user.email, title,dominio, settings.EMAIL_CLIENTE)

def send_reset_confirmation(user, dominio):
	title   = _("Reimposta la password")
	invia_mail(user,'send_reset_confirmation',user.email, title, dominio, settings.EMAIL_CLIENTE)

def send_username(user, dominio):
	title = _("Il tuo nome utente")
	invia_mail(user,'send_username',user.email, title, dominio, settings.EMAIL_CLIENTE)


def conferma(request, confirmation_code, idusername):
	try:
		user = User.objects.get(id=idusername)
		p = user.profilo
		if p.confirmation_code == confirmation_code:
			user.is_active = True
			user.save()

politicalfeedback_client/apps/accounts/templates/accounts_old/attivazione.html
{% extends "base.html" %}
{% load i18n %}

{% block testata %}
	{% include "_/testata.html" %}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumbs">
  <li><a href="/">Home</a></li>
  <li><a href="/accounts/attivazione">Attivazione</a></li>
</ul>
{% endblock %}

{% block content %}
<div class="row">
	<div class="small-12 columns panel" >
		<h4>{% trans "Qui potrai attivare le funzionalità a pagamento." %}</h4>
	</div>

	<p><strong>PulizieFacile</strong> nelle sue funzionalità di base è <strong>completamente gratuito</strong> e rimarrà tale.</p>

	<p>Abbiamo deciso di mettere a pagamento delle funzionalità aggiuntive rispetto al vecchio software in modo da poter mantenere in vita la piattaforma e aumentare lo sviluppo anche attraverso la Vostra collaborazione con il nuovo sistema di suggerimenti e segnalazioni.</p>

	<p><em>Ogni account ha una data di scadenza e il costo di ogni servizio verrà calcolato da oggi alla data di scadenza. Se non si è mai attivato nulla alla prima attivazione la scadenza viene fissata ad un'anno da oggi. La scadenza è SOLO per i servizi a pagamento.</em></p>

	<h3 class="panel">Scadenza servizi {{ scadenza|date:"d/m/Y"}}</h3>

	<form>
	<div class="row">
		<div class="large-8 columns" >
		<h4>Documenti Di Trasporto</h4>
		<p>Questa funzionalità è già presente in modalità gratuita nella fattura. Infatti nella modifica della fattura è possibile attivare l'opzione <em>accompagnatoria</em> e la fattura diventerà anche documento di trasporto.</p>

		<p>Questa funzionalità aggiunge la possibilità di fare DDT indipendenti</p>
		</div>

		<div class="large-4 columns">
		<ul class="pricing-table">
		  <li class="title">Servizio DDT</li>
		  <li class="price">8,00€</li>
		  <li class="description">fino a data di scadenza (IVA esclusa)</li>
		  <li class="bullet-item">creazione documenti di trasporto</li>
		  
		  {% if DDT_trial %}
		  <li class="bullet-item">
		  	<span class="pagato"><strong>Versione di prova attiva</strong></span>
		  </li>
		  <li class="bullet-item"><a href="/accounts/registrasegnalazione/">fai le Tue segnalazioni su questo modulo</a></li>
		  {% else %}
		  <li class="cta-button">
		  <a class="button" href="#"><i class="fa fa-shopping-cart"></i> Aggiungi</a>
		  </li>
		  {% endif %}
		</ul>
		</div>

	</div>

	<div class="row">
		<div class="large-8 columns" >
		<h4>Acquisti e Cespiti</h4>
		<p>Questa funzionalità permette l'inserimento delle fatture di acquisto e il caricamento nei cespiti aziendali dei materiali acquistati.</p>

		<p>Attivandola sarà possibile avere il bilancio esatto del trimestre e il conteggio IVA.</p>
		</div>

		<div class="large-4 columns">
		<ul class="pricing-table">
		  <li class="title">Servizio Acquisti</li>
		  <li class="price">12,00€</li>
		  <li class="description">fino a data di scadenza (IVA esclusa)</li>
		  <li class="bullet-item">inserimento fatture di acquisto e cespiti</li>
		  
		  {% if DDT_trial %}
		  <li class="bullet-item">
		  	<span class="pagato"><strong>Versione di prova attiva</strong></span>
		  </li>
		  <li class="bullet-item"><a href="/accounts/registrasegnalazione/">fai le Tue segnalazioni su questo modulo</a></li>
		  {% else %}
		  <li class="cta-button">
		  <a class="button" href="#"><i class="fa fa-shopping-cart"></i> Aggiungi</a>
		  </li>
		  {% endif %}
		</ul>
		</div>

	</div>
	</form>

</div>
{% endblock %}

politicalfeedback_client/apps/accounts/templates/accounts_old/benvenuto.html
{% extends "accounts/login.html" %}
{% load i18n %}


{% block alert %}
<div data-alert class="alert-box">
		<h2>{% trans "Benvenuto" %}</h2>
		<p>{% trans "Il Tuo account è stato confermato! Ora puoi effettuare il login." %}
		<a href="#" class="close">&times;</a>
</div>
{% endblock %}

politicalfeedback_client/apps/accounts/templates/accounts_old/errorecambio.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block testata %}
	{% include "_/testata_sito.html" %}
{% endblock %}

{% block content %}
<div class="row">
	<div class="small-12 columns panel" >
	{% trans "C'è stato un errore nel cambio password" %}
	</div>
</div>

{% endblock %}

politicalfeedback_client/apps/accounts/templates/accounts_old/registra.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block testata %}
	{% include "_/testata_sito.html" %}
{% endblock %}

{% block content %}


<br />
<div class="row">
	<div class="small-7 columns panel" >
		<h2>{% trans "Registrazione" %}</h2>
		{% if form.non_field_errors %}
			<div class="alert-box alert">{{ form.non_field_errors }}</div>
		{% endif %}
		<form  action="/accounts/registra/" method="post" enctype="multipart/form-data" data-abide>
		{% csrf_token %}
		{{ form.errors }}

			<div class="row">
				

			    <div class="large-4 columns">
			    	<label>{% trans "Foto" %}
			        	{{ form.avatar }}
			      	</label>
			      	<small class="error">{% trans "Inserisci la Tua foto" %}</small>
			    </div>

			</div>
			<div class="row">
				<div class="large-6 columns">
			    	<label>{% trans "Nome" %} <small>richiesto</small>
			        	{{ form.first_name }}
			      	</label>
			      	<small class="error">{% trans "Inserisci il tuo nome" %}</small>
			    </div>
				<div class="large-6 columns">
			    	<label>{% trans "Cognome" %} <small>richiesto</small>
			        	{{ form.last_name }}
			      	</label>
			      	<small class="error">{% trans "Inserisci il tuo cognome" %}</small>
			    </div>
			</div>
			

			<div class="row">
			    <div class="large-8 columns">
			    	<label>{% trans "Email" %} <small>richiesto</small> <span data-tooltip aria-haspopup="true" class="has-tip right" title="Se utilizzavi il vecchio software usa la stessa mail per riuscire ad importare i dati"> <i class="fa fa-info-circle"></i> Avevi il vecchio software?</span>
			        	{{ form.email }}
			      	</label>
			      	<small class="error">{% trans "Il nome utente è obbligatorio e deve essere un indirizzo email" %}</small>
			    </div>
			    <div class="large-4 columns">
			    	<label>{% trans "Telefono" %} <small>richiesto</small>
			        	{{ form.telefono }}
			      	</label>
			      	<small class="error">{% trans "Devi inserire un recapito telefonico" %}</small>
			    </div>
			</div>

			<div class="row">
			    <div class="large-8 columns">
			    	<label>{% trans "indirizzo" %} <small>richiesto</small>
			        	{{ form.indirizzo }}
			      	<small class="error">{{ form.indirizzo.errors }}</small>
			    </div>

			    <div class="large-4 columns">
			    	<label>{% trans "civico/civici" %} <small>richiesto</small>
			        	{{ form.civico }}
			      	</label>
			      	<small class="error">{{ form.civico.errors }}</small>
			    </div>
			</div>
			<div class="row">
			   
			    <div class="large-3 columns">
			    	<label>{% trans "provincia" %} <small>richiesto</small>
			    		{{ form.provincia }}
			      	</label>
			      	<small class="error">{{ form.provincia.errors }}</small>
			    </div>
			    <div class="large-3 columns">
			    	<label>{% trans "città" %} <small>richiesto</small>
			    		{{ form.citta }}
			      	</label>
			      	<small class="error">{{ form.citta.errors }}</small>
			    </div>
			     <div class="large-3 columns">
			    	<label>{% trans "CAP" %}
			    		{{ form.cap }}
			      	</label>
			      	<small class="error">{{ form.cap.errors }}</small>
			    </div>
			</div>

			<div class="row">
			    <div class="large-12 columns password-field">
			    	<label>{% trans "Password (almeno 6 caratteri)" %} <small>richiesto</small>
			        	{{ form.password }}
			      	</label>
			      	<small class="error">{% trans "Devi compilare la password" %}</small>
			    </div>
				<div class="large-12 columns password-confirmation-field">
				   	<label>{% trans "Conferma Password" %} <small>required</small>
				     	<input type="password" required data-equalto="id_password">
				   	</label>
				   	<small class="error">{% trans "La password non combacia" %}</small>
				</div>
			</div>



			<p class="form-control-static grigioscuro"><small>
				{% url 'django.contrib.auth.views.login' as anchor_url %}
				{% blocktrans with anchor='<a href="'|add:anchor_url|add:'">'|safe %}
					Registrandomi, dichiaro di aver preso visione dell'{{ anchor }}informativa sulla privacy</a> di questo sito e di prestare il consenso al trattamento dei miei dati personali.
				{% endblocktrans %}
			</small></p>

			<button type="submit" class="btn btn-primary"><strong>{% trans "Crea il tuo account" %}</strong> &nbsp;<i class="fa fa-arrow-right"></i>


		</form>
	</div>
	<div class="small-4 columns">
		<div class="panel">
		<h4>{% trans "Attiva subito un account" %}</h4>
		<p class="grigioscuro">{% trans "Registrati per iniziare ad usare il software:" %}</p>
		<ul class="fa-ul grigioscuro">
			<li><i class="fa-li fa fa-check text-success"></i>{% trans "Strumenti collaborazivi." %}</li>
		</ul>
		</div>

		<h4>Se ti sei già registrato e non ti è arrivata la mail di attivazione, clicca qui sotto per reinviarla.</h4>
		<a href="#" data-reveal-id="attivazione" class="button extend">Reinvia attivazione</a>
	</div>
</div>


<!-- Reinvia attivazione -->
	

		<div id="attivazione" class="reveal-modal" data-reveal>
		  	<h4>{% trans "Reinviamo il codice di attivazione" %}</h4>
		  	<p class="grigioscuro">{% trans "Inserisci l'indirizzo e-mail con cui ti sei registrato e ti invieremo le istruzioni per attivare il Tuo account." %}</p>
			<hr>

			<form role="form" action="/accounts/rimandaattivazione/" method="post" data-abide>
			{% csrf_token %}
			<div class="row">
			    <div class="large-10 columns">
			    	<label>{% trans "Email" %} <small>richiesto</small>
			        	<input name="email" id="email_reset" type="email" placeholder="{% trans "email" %}" aria-describedby="emailHelp" required/>
			      	</label>
			      	<small class="error">{% trans "Inserisci una email valida." %}</small>
			    </div>
			</div>

			<div class="row">
				<div class="large-12 columns">
				<button  class="right" type="submit"><strong>{% trans "Reinvia" %}</strong> &nbsp;<i class="fa fa-arrow-right"></i></button>
				</div>
			</div>

		  	<a class="close-reveal-modal">&#215;</a>
		  	</form>
		</div>


{% endblock %}

{% block extraprescripts %}
<script type="text/javascript" src='{% static 'foundation/js/foundation/foundation.abide.js' %}'></script>
<script type="text/javascript">
$('#id_provincia').change(function(){
	$("#id_citta").load("/anagrafiche/elencocitta/"+$('#id_provincia').val()+"/");
	$("#id_citta").removeClass('hide');
});
</script>
{% endblock %}